name = "NCBITaxonomy"
uuid = "f88b31d2-eb98-4433-b52d-2dd32bc6efce"
authors = ["Timothée Poisot <timothee.poisot@umontreal.ca>"]
version = "0.1.0"

[deps]
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[compat]
julia = "1.3"
