name: Documentation


on:
  release:
    type: [published,edited]
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.5'
      - uses: julia-actions/julia-buildpkg@latest
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
